<?php
/**
 * @file
 * Code for the cod_registration feature.
 */

include_once 'cod_registration.features.inc';
include_once 'cod_registration.admin.inc';
module_load_include('admin.inc','ticket', 'includes/ticket_registration');

/*
 * COD Registration initial page
 */
function cod_registration_menu() {
  $items['node/%node/check-in/%user'] = array(
    'title'             => 'Registration',
    'access callback'   => 'cod_registration_reg_perms',
    'page callback'     => 'drupal_get_form',
    'page arguments'    => array('cod_registration_checkin', 1,3),
    'type'              => MENU_CALLBACK,
  );

  // Change the tickets page to move configuration there.
  $items['admin/conference/%node/tickets/add'] = array(
    'title' => 'Add Ticket',
    'type' => MENU_LOCAL_ACTION,
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ticket_type_edit_form', new TicketTypeEntity(array('field_name' => 'field_event_tickets')), 2),
    'access arguments' => array('administer ticket'),
    'file path' => drupal_get_path('module', 'ticket') . '/includes',
    'file' => 'ticket_type.admin.inc',
   );

  return $items;
}

/**
 * Implements hook_cod_default_permissions().
 */
function cod_registration_cod_default_permissions() {
  return array(
    'user_permission' => array('cod_registration'),
  );
}

/**
 * Implements hook_form_alter().
 * Remove tickets from the event edit form.
 */
function cod_registration_form_event_node_form_alter(&$form, &$form_state, $form_id) {
  if (isset($form['#node_edit_form']) && isset($form['field_event_tickets'])) {
    drupal_set_message(t("Ticket configuration has moved to the !tickets tab.", array('!tickets' => l('tickets', 'admin/conference/'.$form['nid']['#value'] .'/edit'))));
    $form['field_event_tickets']['#access'] = FALSE;
  }
}

/**
 * @param $form
 * @param $form_state
 * @param $form_id
 *
 * Redirect users saving tickets back to the tickets management page.
 */
function cod_registration_form_ticket_type_edit_form_alter(&$form, &$form_state, $form_id) {
  $form['field_event_tickets'][LANGUAGE_NONE][$form_state['field_delta']]['submit']['#submit'][] = 'cod_registration_form_ticket_type_edit_submit';
}

function cod_registration_form_ticket_type_edit_submit($form, &$form_state) {
  $form_state['redirect'] = 'admin/conference/' . $form_state['node']->nid . '/tickets';
}