<?php
/**
 * @file
 * dgc_extras.features.field_instance.inc
 */

/**
 * Implements hook_field_default_field_instances().
 */
function dgc_extras_field_default_field_instances() {
  $field_instances = array();

  // Exported field_instance: 'user-user-field_government_employee'.
  $field_instances['user-user-field_government_employee'] = array(
    'bundle' => 'user',
    'default_value' => array(
      0 => array(
        'value' => 0,
      ),
    ),
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'list',
        'settings' => array(),
        'type' => 'list_default',
        'weight' => 11,
      ),
      'full' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'user',
    'field_name' => 'field_government_employee',
    'label' => 'Government Employee',
    'required' => 0,
    'settings' => array(
      'user_register_form' => 0,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'options',
      'settings' => array(
        'display_label' => 1,
      ),
      'type' => 'options_onoff',
      'weight' => 6,
    ),
  );

  // Translatables
  // Included for use with string extractors like potx.
  t('Government Employee');

  return $field_instances;
}
