name = Govcon Simple
description = Custom Layout for GovCon Theme.
preview = preview.png
template = govcon-simple-layout

; Regions
regions[navigation]     = Navigation bar
regions[branding]       = Branding
regions[header]         = Header
regions[banner]         = Banner
regions[highlighted]    = Highlighted
regions[help]           = Help
regions[content]        = Content
regions[sidebar_first]  = First sidebar
regions[sidebar_second] = Second sidebar
regions[lower_first]	= First Lower Content Area
regions[lower_second]	= Second Lower Content Area
regions[footer]         = Footer

; Stylesheets
stylesheets[all][] = css/layouts/govcon-simple/govcon-simple.layout.css
